// Generated by gencpp from file manta/Imu2.msg
// DO NOT EDIT!


#ifndef MANTA_MESSAGE_IMU2_H
#define MANTA_MESSAGE_IMU2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manta
{
template <class ContainerAllocator>
struct Imu2_
{
  typedef Imu2_<ContainerAllocator> Type;

  Imu2_()
    : x(0.0)  {
    }
  Imu2_(const ContainerAllocator& _alloc)
    : x(0.0)  {
    }



   typedef float _x_type;
  _x_type x;




  typedef boost::shared_ptr< ::manta::Imu2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manta::Imu2_<ContainerAllocator> const> ConstPtr;

}; // struct Imu2_

typedef ::manta::Imu2_<std::allocator<void> > Imu2;

typedef boost::shared_ptr< ::manta::Imu2 > Imu2Ptr;
typedef boost::shared_ptr< ::manta::Imu2 const> Imu2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manta::Imu2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manta::Imu2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manta

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'manta': ['/home/pi/manta_ws/src/manta/msg'], 'geometry_msgs': ['/home/pi/manta_ws/src/common_msgs/geometry_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manta::Imu2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manta::Imu2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manta::Imu2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manta::Imu2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manta::Imu2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manta::Imu2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manta::Imu2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abd5d1e9c3ac157a0df3ba27b65d3384";
  }

  static const char* value(const ::manta::Imu2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabd5d1e9c3ac157aULL;
  static const uint64_t static_value2 = 0x0df3ba27b65d3384ULL;
};

template<class ContainerAllocator>
struct DataType< ::manta::Imu2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manta/Imu2";
  }

  static const char* value(const ::manta::Imu2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manta::Imu2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
";
  }

  static const char* value(const ::manta::Imu2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manta::Imu2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Imu2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manta::Imu2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manta::Imu2_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANTA_MESSAGE_IMU2_H
