#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/pi/manta_ws/devel_isolated/geometry:$CMAKE_PREFIX_PATH"
export CPATH="/home/pi/manta_ws/devel_isolated/geometry/include:$CPATH"
export LD_LIBRARY_PATH="/home/pi/manta_ws/devel_isolated/geometry/lib:/home/pi/manta_ws/devel_isolated/geometry/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/diagnostics/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/diagnostic_common_diagnostics/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/diagnostic_updater/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/diagnostic_analysis/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/common_msgs/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib/arm-linux-gnueabihf:/opt/ros/indigo/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib:/home/pi/manta_ws/devel_isolated/diagnostics/lib:/home/pi/manta_ws/devel_isolated/diagnostic_common_diagnostics/lib:/home/pi/manta_ws/devel_isolated/diagnostic_updater/lib:/home/pi/manta_ws/devel_isolated/diagnostic_analysis/lib:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib:/home/pi/manta_ws/devel_isolated/common_msgs/lib:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib:/opt/ros/indigo/lib"
export PATH="/home/pi/manta_ws/devel_isolated/geometry/bin:$PATH"
export PKG_CONFIG_PATH="/home/pi/manta_ws/devel_isolated/geometry/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/geometry/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostics/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_common_diagnostics/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_updater/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_analysis/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/common_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib/arm-linux-gnueabihf/pkgconfig:/opt/ros/indigo/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostics/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_common_diagnostics/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_updater/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_analysis/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/common_msgs/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib/pkgconfig:/opt/ros/indigo/lib/pkgconfig"
export PYTHONPATH="/home/pi/manta_ws/devel_isolated/geometry/lib/python2.7/dist-packages:$PYTHONPATH"
export ROS_PACKAGE_PATH="/home/pi/manta_ws/src/geometry/geometry:$ROS_PACKAGE_PATH"