#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/pi/manta_ws/devel_isolated/pluginlib:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics:/home/pi/manta_ws/devel_isolated/kdl_conversions:/home/pi/manta_ws/devel_isolated/eigen_conversions:/home/pi/manta_ws/devel_isolated/nav_msgs:/home/pi/manta_ws/devel_isolated/manta:/home/pi/manta_ws/devel_isolated/geometry_msgs:/home/pi/manta_ws/devel_isolated/geometry:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure:/home/pi/manta_ws/devel_isolated/diagnostic_msgs:/home/pi/manta_ws/devel_isolated/common_msgs:/home/pi/manta_ws/devel_isolated/actionlib_msgs:/home/pi/manta_ws/devel:/opt/ros/indigo:/home/pi/manta_ws/devel_isolated/orocos_kdl"
export CPATH="/home/pi/manta_ws/devel_isolated/pluginlib/include:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics/include:/home/pi/manta_ws/devel_isolated/kdl_conversions/include:/home/pi/manta_ws/devel_isolated/eigen_conversions/include:/home/pi/manta_ws/devel_isolated/nav_msgs/include:/home/pi/manta_ws/devel_isolated/manta/include:/home/pi/manta_ws/devel_isolated/geometry_msgs/include:/home/pi/manta_ws/devel_isolated/geometry/include:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/include:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/include:/home/pi/manta_ws/devel_isolated/common_msgs/include:/home/pi/manta_ws/devel_isolated/actionlib_msgs/include:/home/pi/manta_ws/devel/include:/opt/ros/indigo/include:/home/pi/manta_ws/devel_isolated/orocos_kdl/include"
export LD_LIBRARY_PATH="/home/pi/manta_ws/devel_isolated/pluginlib/lib:/home/pi/manta_ws/devel_isolated/pluginlib/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/kdl_conversions/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/eigen_conversions/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/nav_msgs/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/manta/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/geometry_msgs/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/geometry/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/common_msgs/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel/lib/arm-linux-gnueabihf:/opt/ros/indigo/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics/lib:/home/pi/manta_ws/devel_isolated/kdl_conversions/lib:/home/pi/manta_ws/devel_isolated/eigen_conversions/lib:/home/pi/manta_ws/devel_isolated/orocos_kdl/lib:/home/pi/manta_ws/devel_isolated/orocos_kdl/lib/arm-linux-gnueabihf:/home/pi/manta_ws/devel_isolated/nav_msgs/lib:/home/pi/manta_ws/devel_isolated/manta/lib:/home/pi/manta_ws/devel_isolated/geometry_msgs/lib:/home/pi/manta_ws/devel_isolated/geometry/lib:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib:/home/pi/manta_ws/devel_isolated/common_msgs/lib:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib:/home/pi/manta_ws/devel/lib:/opt/ros/indigo/lib"
export PATH="/home/pi/manta_ws/devel_isolated/pluginlib/bin:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics/bin:/home/pi/manta_ws/devel_isolated/kdl_conversions/bin:/home/pi/manta_ws/devel_isolated/eigen_conversions/bin:/home/pi/manta_ws/devel_isolated/nav_msgs/bin:/home/pi/manta_ws/devel_isolated/manta/bin:/home/pi/manta_ws/devel_isolated/geometry_msgs/bin:/home/pi/manta_ws/devel_isolated/geometry/bin:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/bin:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/bin:/home/pi/manta_ws/devel_isolated/common_msgs/bin:/home/pi/manta_ws/devel_isolated/actionlib_msgs/bin:/home/pi/manta_ws/devel/bin:/opt/ros/indigo/bin:/home/pi/manta_ws/devel_isolated/orocos_kdl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"
export PKG_CONFIG_PATH="/home/pi/manta_ws/devel_isolated/pluginlib/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/pluginlib/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/kdl_conversions/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/eigen_conversions/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/nav_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/manta/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/geometry_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/geometry/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/common_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel/lib/arm-linux-gnueabihf/pkgconfig:/opt/ros/indigo/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/kdl_conversions/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/eigen_conversions/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/orocos_kdl/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/orocos_kdl/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/manta_ws/devel_isolated/nav_msgs/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/manta/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/geometry_msgs/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/geometry/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/common_msgs/lib/pkgconfig:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib/pkgconfig:/home/pi/manta_ws/devel/lib/pkgconfig:/opt/ros/indigo/lib/pkgconfig"
export PYTHONPATH="/home/pi/manta_ws/devel_isolated/pluginlib/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/orocos_kinematics_dynamics/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/kdl_conversions/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/eigen_conversions/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/nav_msgs/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/manta/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/geometry_msgs/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/geometry/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/dynamic_reconfigure/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/diagnostic_msgs/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/common_msgs/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/actionlib_msgs/lib/python2.7/dist-packages:/home/pi/manta_ws/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages:/home/pi/manta_ws/devel_isolated/orocos_kdl/lib/python2.7/dist-packages:/home/pi/manta_ws/devel/lib/python2.7/dist-packages/"
export ROS_PACKAGE_PATH="/home/pi/manta_ws/src/pluginlib:$ROS_PACKAGE_PATH"